[package]
name = "q-lang"
version = "0.1.0"
edition = "2024"

[workspace]
resolver = "3"
members = ["lexer", "utils"]

[dependencies]
load_file = "1.0.1"
lexer = { path = "lexer" }
utils = { path = "utils" }
anyhow = "1.0.99"
